version: '3'
services:
    storeconnect-webvowl:
        image: storeconnect/webvowl:latest
        container_name: storeconnect-webvowl
        ports:
            - "8081:8080"
        volumes:
            - './data:/data' 
