version: '3'
services:
    webvowl:
        container_name: webvowl
        #image: visualdataweb/webvowl:latest (not available yet, see https://github.com/VisualDataWeb/WebVOWL/issues/111 for more detais)
        image: abourdon/webvowl:latest
        ports:
            - "8080:8080"
        volumes:
            - './data:/data' 
